cc_library(
    name = "tclap",
    hdrs = glob(["thirdparty_build/include/tclap/**/*.h"]),
    copts = ["-I/usr/include/tclap"],
    linkopts = [],
    visibility = ["//visibility:public"],
    linkstatic=False,
)
