cc_library(
    name = "flat_hash_map",
    hdrs = glob(["thirdparty_build/include/absl/**/*.h"]),
    copts = ["-I/usr/include/absl"],
    linkopts = [
        "-labsl_container_libhash_generator_testing",
        "-labsl_container_libraw_hash_set",
        "-labsl_container_libtest_instance_tracker",
        "-labsl_hash_libcity",
        "-labsl_hash_libhash",
    ],
    visibility = ["//visibility:public"],
    linkstatic = False,
)

cc_library(
    name = "flat_hash_set",
    hdrs = glob(["thirdparty_build/include/absl/**/*.h"]),
    copts = ["-I/usr/include/absl"],
    linkopts = [
        "-labsl_container_libhash_generator_testing",
        "-labsl_container_libraw_hash_set",
        "-labsl_container_libtest_instance_tracker",
        "-labsl_hash_libcity",
        "-labsl_hash_libhash",
    ],
    visibility = ["//visibility:public"],
    linkstatic = False,
)

cc_library(
    name = "inlined_vector",
    hdrs = glob(["thirdparty_build/include/absl/**/*.h"]),
    copts = ["-I/usr/include/absl"],
    linkopts = [
        "-labsl_container_libhash_generator_testing",
        "-labsl_container_libraw_hash_set",
        "-labsl_container_libtest_instance_tracker",
        "-labsl_hash_libcity",
        "-labsl_hash_libhash",
    ],
    visibility = ["//visibility:public"],
    linkstatic = False,
)

cc_library(
    name = "node_hash_map",
    hdrs = glob(["thirdparty_build/include/absl/**/*.h"]),
    copts = ["-I/usr/include/absl"],
    linkopts = [
        "-labsl_container_libhash_generator_testing",
        "-labsl_container_libraw_hash_set",
        "-labsl_container_libtest_instance_tracker",
        "-labsl_hash_libcity",
        "-labsl_hash_libhash",
    ],
    visibility = ["//visibility:public"],
    linkstatic = False,
)

cc_library(
    name = "node_hash_set",
    hdrs = glob(["thirdparty_build/include/absl/**/*.h"]),
    copts = ["-I/usr/include/absl"],
    linkopts = [
        "-labsl_container_libhash_generator_testing",
        "-labsl_container_libraw_hash_set",
        "-labsl_container_libtest_instance_tracker",
        "-labsl_hash_libcity",
        "-labsl_hash_libhash",
    ],
    visibility = ["//visibility:public"],
    linkstatic = False,
)
