cc_library(
    name = "http_parser",
    hdrs = glob(["thirdparty_build/include/http_parser.h"]),
    copts = [],
    linkopts = ["-lhttp_parser"],
    visibility = ["//visibility:public"],
    linkstatic = False,
)
