cc_library(
    name = "all",
    hdrs = glob(["thirdparty_build/include/nghttp2/**/*.h"]),
    copts = [],
    linkopts = ["-lnghttp2"],
    visibility = ["//visibility:public"],
    linkstatic=False,
)
