cc_library(
    name = "all",
    hdrs = glob(["thirdparty_build/include/yaml-cpp/**/*.h"]),
    copts = [],
    linkopts = ["-lyaml-cpp"],
    visibility = ["//visibility:public"],
    linkstatic = False,
)
