cc_library(
    name = "libcircllhist",
    hdrs = glob(["thirdparty_build/include/circllhist.h"]),
    copts = [],
    linkopts = ["-lcircllhist"],
    visibility = ["//visibility:public"],
    linkstatic=False,
)
