cc_library(
    name = "all",
    hdrs = glob(["thirdparty_build/include/pb*.h"]),
    copts = [],
    linkopts = ["-lprotobuf-nanopb"],
    visibility = ["//visibility:public"],
    linkstatic = False,
)
