cc_library(
    name = "memory",
    hdrs = glob(["thirdparty_build/include/absl/**/*.h"]),
    copts = ["-I/usr/include/absl"],
    linkopts = [],
    visibility = ["//visibility:public"],
    linkstatic = False,
)
