cc_library(
    name = "all",
    hdrs = glob(["thirdparty_build/include/jwt_verify_lib/**/*.h"]),
    copts = [],
    linkopts = ["-ljwt_verify_lib"],
    visibility = ["//visibility:public"],
    linkstatic = False,
)
