cc_library(
    name = "msgpack",
    hdrs = glob([
        "thirdparty_build/include/msgpack.h",
        "thirdparty_build/include/msgpack.hpp",
    ]),
    copts = [],
    linkopts = ["-lmsgpackc"],
    visibility = ["//visibility:public"],
    linkstatic = False,
)
