cc_library(
    name = "xxhash",
    hdrs = glob(["thirdparty_build/include/xxhash.h"]),
    copts = [],
    linkopts = ["-lxxhash"],
    visibility = ["//visibility:public"],
    linkstatic=False,
)
