cc_library(
    name = "rapidjson",
    hdrs = glob(["thirdparty_build/include/rapidjson/**/*.h"]),
    copts = ["-I/usr/include/rapidjson"],
    linkopts = [],
    visibility = ["//visibility:public"],
    linkstatic=False,
)
